trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:

- stage: deployToDev
  displayName: Deploy to DEV  
  jobs:
    - deployment: dev
      displayName: Deploy to sqlServer

      environment: azure-dev

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            - task: CmdLine@2
              displayName: clone postgresql samples repo
              inputs:
                script: |
                  git clone https://github.com/MaciejReplin/DbSourceControl\Yuniql $(Build.SourcesDirectory)\yuniql\new\

            - task: UseYUNIQLCLI@1
              displayName: yuniql install
              inputs:
                version: 'latest'

            - task: RunYUNIQLCLI@1
              displayName: yuniql run
              inputs:
                version: 'latest'
                connectionString: '$(DBConnectionString)'
                workspacePath: '$(Build.SourcesDirectory)\yuniql\new'
                targetPlatform: 'SqlServer'
                additionalArguments: '--debug'
